### ISSUE TITLE
The movie menu gets corrupted when I use this and the DLC

### ISSUE THREAD

**Issue by Krathoon** [Sampsca/BGEE-Classic-Movies#8]
When I have Dragonspear installed and I use classic movies, the movie menu gets corrupted. It has these entries with tiny text for some reason.
If I uninstall the DLC, it works fine.

**Comment by Sampsca** [comment]
There are three avenues for playing BGEE, with our without SoD.  They are 1) Directly from Beamdog, 2) Steam, 3) GoG.  You haven't specified, but I'm guessing you're using Steam.  Regardless, if you are using either of the second two methods, the process for modding a SoD game is this:  Install BGEE; If playing SoD and it is a separate DLC, install it next; If playing SoD as a DLC, install [DlcMerger](https://github.com/Argent77/A7-DlcMerger); Install mods as desired.  This order is non-negotiable, and uninstalling something from the middle of this order corrupts the entire installation.  If you are following this process and still having issues, then I am going to need more information in order to help you diagnose this issue.

**Comment by Krathoon** [comment]
I installed the gog version. It comes with the DLC installed. Sounds like I need to try dlcmerger.On Dec 23, 2022 9:17 PM, Sampsca ***@***.***> wrote:
There are three avenues for playing BGEE, with our without SoD.  They are 1) Directly from Beamdog, 2) Steam, 3) GoG.  You haven't specified, but I'm guessing you're using Steam.  Regardless, if you are using either of the second two methods, the process for modding a SoD game is this:  Install BGEE; If playing SoD and it is a separate DLC, install it next; If playing SoD as a DLC, install DlcMerger; Install mods as desired.  This order is non-negotiable, and uninstalling something from the middle of this order corrupts the entire installation.  If you are following this process and still having issues, then I am going to need more information in order to help you diagnose this issue.
